---
title: "Plots of the Mittag-Leffler distributions"
author: "Gurtek Gill, Peter Straka"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Vignette Title}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r}
library(MittagLeffler)
alpha <- 0.95
scale <- 2
n <- 100000
cutoff <- 2 * scale
```

## First type

```{r}
r <- rml(n = n, alpha = alpha, scale=scale)
edfun <- ecdf(r)
x <- seq(0.01,10,0.01)
plot(x,edfun(x), xlim=c(0,10), type='l')
y <- pml(q = x, alpha = alpha, scale=scale)
lines(x,y,col=2)
z <- 1-exp(-(x/scale)^alpha)
lines(x,z, lty=2)


x <- exp(seq(-10,10,0.01))
y <- 1-edfun(x)
plot(x,y, type='l', log='xy')
y <- pml(q = x, alpha = alpha, scale=scale, lower.tail = FALSE)
lines(x,y, col=2)
# power law for large values
z <- x^(-alpha)
lines(x,z, lty=2)
# stretched exponential for small values
w <- exp(-(x/scale)^alpha)
lines(x,w, lty=2)
```


```{r}
cutoff <- 10
fac <- sum(r <= cutoff) / n
r <- r[r <= cutoff]
hist(r, freq = FALSE, breaks = 50)
x <- seq(0.01,cutoff,0.01)
y <- dml(x = x, alpha = alpha, scale=scale) / fac
lines(x,y, col=2)
```




## Second type

```{r}
library(MittagLeffler)
n <- 10^5
alpha <- 0.6
r <- rml(n = n, alpha = alpha, scale=scale, second.type = TRUE)
plot(ecdf(r), xlim=c(0,cutoff))
x <- seq(0.01,cutoff,0.01)
y <- pml(q = x, alpha = alpha, scale=scale, second.type = TRUE)
lines(x,y, col=2)
```

Draw the density version with histograms, which looks nicer:

```{r, warning=FALSE}
hist(r, freq = FALSE, breaks = 20)
x <- seq(0.01,cutoff,0.01)
y <- dml(x = x, alpha = alpha, scale=scale, second.type = TRUE)
lines(x,y, col=2)
```

